server:
  port: 8080
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 10.36.1.48
    port: 6379
    password:    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
#    jedis:
#      pool:
#        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10      # 连接池中的最大空闲连接
#        min-idle: 5       # 连接池中的最小空闲连接
#zuul:
#  routes:
#    risk:
#      path: /risk/v1/**
#      url: http://localhost:9090/risk/v1


#不使用注册中心的情况下也使用负载均衡  http://localhost:8080/kltb/risk/v1/apply
zuul:
  routes:
    risk-provider:
      path: /kltb/**
      serviceId: risk-service
  ratelimit:
    enabled: true
    repository: redis   #redis 集群服务限流 所有数据都存储到redis
    default-policy:  #每个Url 所有服务在 1 秒内只能有 100 次请求且所有请求时间总和不得超过 30 秒
      limit: 1000
      quota: 10
      refresh-interval: 10
      type: url   #每个Url
#    policies:  #60秒内访问次数不得查过10次且访问时间这不得超过50秒
#      risk-service:  #针对单个服务 需要有注册中心
#        limit: 2
#        quota: 50
#        refresh-interval: 60
ribbon:
  eureka:
    enabled: false
risk-service:
  ribbon:
    listOfServers: http://localhost:9090   #接nginx地址

log:
  path: /apps/company-gate

logging:
  level:
    com.netflix: DEBUG